[package]
name = "lottery"
version = "0.0.4"
authors = ["ooshlablu"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
structopt = "0.3"
